### ISSUE TITLE
Pesquisa de Mercado e Benchmarking

### ISSUE THREAD

**Issue by projeto-grafica** [projeto-grafica/projeto-grafica-bocaboa#4]
Bench no mercado e documentação (1 dia)
Bench fora da área do cliente e documentação (1 dia)

**Comment by pelinsarix** [comment]
-> CEP na barra de navegação (mercado livre)
-> Comparação e produtos similares do lado do produto (kabum)
-> STEPS para a montagem do produto e descrição e avaliação do produto atual , step atual (kabum)
-> Carrinho (elementor)
-> Avaliação de produtos (elementor)
-> página inicial sobre o que é o produto, fluxo mais rápido(Make a cake)
-> acesso rápido no FAQ (netshoes)
-> informações rápidas, pontos fidelidade, loading, muitas informações(growth)
-> carrinho (amazon)
-> ux (apple)
-> 404 (pontofrio)

Nicho:
-> compra online e whatsapp (Grafica plutão), descontos??
-> design e gabarito, prazo de produção e frete (FuturaUM)
-> quantidade de detalhes, encaixar imagem, gabarito (grafica paulista)
-> passo a passo e dicas para cliente, seção de como fazer(ZAPGRAFICA)
-> chat (graficaonlinesp)
-> organização (printi)
-> metricas e preview (etiquetaseadesivos)
-> personalização, etiquetas (canva)
